apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hro3rhgpx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hro3rhgpx-python 
  name: hro3rhgpx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hro3rhgpx-python 
