apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hro3rhgpx-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:1d620f83d6852f8eb4ff40230ba7a115d64d82a8@sha256:731d8c3c9a5e0fa3c6258de26bc77d40546c31e074c37e98b0c42f6ff3618c85
          name: container-image
